/* tslint:disable */
require("./NewRequest.module.css");
const styles = {
  newRequest: 'newRequest_45ab6eec',
  'ms-TextField': 'ms-TextField_45ab6eec',
  submitButton: 'submitButton_45ab6eec',
  selectContainer: 'selectContainer_45ab6eec',
  customSelect: 'customSelect_45ab6eec',
  section: 'section_45ab6eec',
  table: 'table_45ab6eec',
  tableHeader: 'tableHeader_45ab6eec',
  tableRow: 'tableRow_45ab6eec',
  formRow: 'formRow_45ab6eec',
  'ms-TextField-fieldGroup': 'ms-TextField-fieldGroup_45ab6eec',
  tableWrapper: 'tableWrapper_45ab6eec',
  'ms-Button--default': 'ms-Button--default_45ab6eec',
  customAlert: 'customAlert_45ab6eec',
  selectLabel: 'selectLabel_45ab6eec',
  addButton: 'addButton_45ab6eec',
  deleteButton: 'deleteButton_45ab6eec',
  buttonRow: 'buttonRow_45ab6eec',
  cancelButton: 'cancelButton_45ab6eec',
  popupOverlay: 'popupOverlay_45ab6eec',
  popupContainer: 'popupContainer_45ab6eec',
  popupAppear: 'popupAppear_45ab6eec',
  popupHeader: 'popupHeader_45ab6eec',
  popupBody: 'popupBody_45ab6eec',
  popupFooter: 'popupFooter_45ab6eec',
  popupYesButton: 'popupYesButton_45ab6eec',
  popupNoButton: 'popupNoButton_45ab6eec',
  popupOkButton: 'popupOkButton_45ab6eec',
  validationError: 'validationError_45ab6eec',
  'ms-Dropdown-title': 'ms-Dropdown-title_45ab6eec',
  'react-select-error': 'react-select-error_45ab6eec',
  'react-select__control': 'react-select__control_45ab6eec',
  'textField-159': 'textField-159_45ab6eec',
  textFieldError: 'textFieldError_45ab6eec',
  dropdownError: 'dropdownError_45ab6eec',
  datePickerError: 'datePickerError_45ab6eec',
  errorMessage: 'errorMessage_45ab6eec',
  errorIcon: 'errorIcon_45ab6eec',
  successPopup: 'successPopup_45ab6eec',
  errorPopup: 'errorPopup_45ab6eec',
  successHeader: 'successHeader_45ab6eec',
  errorHeader: 'errorHeader_45ab6eec',
  wrapText: 'wrapText_45ab6eec',
  inputError: 'inputError_45ab6eec',
  'ms-Dropdown-dropdown': 'ms-Dropdown-dropdown_45ab6eec',
  'react-select__value-container': 'react-select__value-container_45ab6eec',
  'react-select__single-value': 'react-select__single-value_45ab6eec',
  'react-select__placeholder': 'react-select__placeholder_45ab6eec',
  'ms-DatePicker-textField': 'ms-DatePicker-textField_45ab6eec',
  projectTypeError: 'projectTypeError_45ab6eec',
  tableDropdownError: 'tableDropdownError_45ab6eec',
  tableDateError: 'tableDateError_45ab6eec',
  tableSelectError: 'tableSelectError_45ab6eec',
  saveDraftButton: 'saveDraftButton_45ab6eec'
};

export default styles;
/* tslint:enable */